package com.alpha.mall.manager.pojo;

import java.util.Date;

public class TMallProductColor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_color.id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_color.shp_id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private Integer shpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_color.shp_ys
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private String shpYs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_color.shfqy
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private Integer shfqy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_color.chjshj
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private Date chjshj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_color.id
     *
     * @return the value of t_mall_product_color.id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_color.id
     *
     * @param id the value for t_mall_product_color.id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_color.shp_id
     *
     * @return the value of t_mall_product_color.shp_id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public Integer getShpId() {
        return shpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_color.shp_id
     *
     * @param shpId the value for t_mall_product_color.shp_id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setShpId(Integer shpId) {
        this.shpId = shpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_color.shp_ys
     *
     * @return the value of t_mall_product_color.shp_ys
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public String getShpYs() {
        return shpYs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_color.shp_ys
     *
     * @param shpYs the value for t_mall_product_color.shp_ys
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setShpYs(String shpYs) {
        this.shpYs = shpYs == null ? null : shpYs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_color.shfqy
     *
     * @return the value of t_mall_product_color.shfqy
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public Integer getShfqy() {
        return shfqy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_color.shfqy
     *
     * @param shfqy the value for t_mall_product_color.shfqy
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setShfqy(Integer shfqy) {
        this.shfqy = shfqy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_color.chjshj
     *
     * @return the value of t_mall_product_color.chjshj
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public Date getChjshj() {
        return chjshj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_color.chjshj
     *
     * @param chjshj the value for t_mall_product_color.chjshj
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setChjshj(Date chjshj) {
        this.chjshj = chjshj;
    }
}