package com.alpha.mall.manager.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TMallProductSkuInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public TMallProductSkuInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andShpBbIsNull() {
            addCriterion("shp_bb is null");
            return (Criteria) this;
        }

        public Criteria andShpBbIsNotNull() {
            addCriterion("shp_bb is not null");
            return (Criteria) this;
        }

        public Criteria andShpBbEqualTo(Integer value) {
            addCriterion("shp_bb =", value, "shpBb");
            return (Criteria) this;
        }

        public Criteria andShpBbNotEqualTo(Integer value) {
            addCriterion("shp_bb <>", value, "shpBb");
            return (Criteria) this;
        }

        public Criteria andShpBbGreaterThan(Integer value) {
            addCriterion("shp_bb >", value, "shpBb");
            return (Criteria) this;
        }

        public Criteria andShpBbGreaterThanOrEqualTo(Integer value) {
            addCriterion("shp_bb >=", value, "shpBb");
            return (Criteria) this;
        }

        public Criteria andShpBbLessThan(Integer value) {
            addCriterion("shp_bb <", value, "shpBb");
            return (Criteria) this;
        }

        public Criteria andShpBbLessThanOrEqualTo(Integer value) {
            addCriterion("shp_bb <=", value, "shpBb");
            return (Criteria) this;
        }

        public Criteria andShpBbIn(List<Integer> values) {
            addCriterion("shp_bb in", values, "shpBb");
            return (Criteria) this;
        }

        public Criteria andShpBbNotIn(List<Integer> values) {
            addCriterion("shp_bb not in", values, "shpBb");
            return (Criteria) this;
        }

        public Criteria andShpBbBetween(Integer value1, Integer value2) {
            addCriterion("shp_bb between", value1, value2, "shpBb");
            return (Criteria) this;
        }

        public Criteria andShpBbNotBetween(Integer value1, Integer value2) {
            addCriterion("shp_bb not between", value1, value2, "shpBb");
            return (Criteria) this;
        }

        public Criteria andShpYsIsNull() {
            addCriterion("shp_ys is null");
            return (Criteria) this;
        }

        public Criteria andShpYsIsNotNull() {
            addCriterion("shp_ys is not null");
            return (Criteria) this;
        }

        public Criteria andShpYsEqualTo(Integer value) {
            addCriterion("shp_ys =", value, "shpYs");
            return (Criteria) this;
        }

        public Criteria andShpYsNotEqualTo(Integer value) {
            addCriterion("shp_ys <>", value, "shpYs");
            return (Criteria) this;
        }

        public Criteria andShpYsGreaterThan(Integer value) {
            addCriterion("shp_ys >", value, "shpYs");
            return (Criteria) this;
        }

        public Criteria andShpYsGreaterThanOrEqualTo(Integer value) {
            addCriterion("shp_ys >=", value, "shpYs");
            return (Criteria) this;
        }

        public Criteria andShpYsLessThan(Integer value) {
            addCriterion("shp_ys <", value, "shpYs");
            return (Criteria) this;
        }

        public Criteria andShpYsLessThanOrEqualTo(Integer value) {
            addCriterion("shp_ys <=", value, "shpYs");
            return (Criteria) this;
        }

        public Criteria andShpYsIn(List<Integer> values) {
            addCriterion("shp_ys in", values, "shpYs");
            return (Criteria) this;
        }

        public Criteria andShpYsNotIn(List<Integer> values) {
            addCriterion("shp_ys not in", values, "shpYs");
            return (Criteria) this;
        }

        public Criteria andShpYsBetween(Integer value1, Integer value2) {
            addCriterion("shp_ys between", value1, value2, "shpYs");
            return (Criteria) this;
        }

        public Criteria andShpYsNotBetween(Integer value1, Integer value2) {
            addCriterion("shp_ys not between", value1, value2, "shpYs");
            return (Criteria) this;
        }

        public Criteria andSkuIdIsNull() {
            addCriterion("sku_id is null");
            return (Criteria) this;
        }

        public Criteria andSkuIdIsNotNull() {
            addCriterion("sku_id is not null");
            return (Criteria) this;
        }

        public Criteria andSkuIdEqualTo(Integer value) {
            addCriterion("sku_id =", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotEqualTo(Integer value) {
            addCriterion("sku_id <>", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdGreaterThan(Integer value) {
            addCriterion("sku_id >", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sku_id >=", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLessThan(Integer value) {
            addCriterion("sku_id <", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLessThanOrEqualTo(Integer value) {
            addCriterion("sku_id <=", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdIn(List<Integer> values) {
            addCriterion("sku_id in", values, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotIn(List<Integer> values) {
            addCriterion("sku_id not in", values, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdBetween(Integer value1, Integer value2) {
            addCriterion("sku_id between", value1, value2, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sku_id not between", value1, value2, "skuId");
            return (Criteria) this;
        }

        public Criteria andShpDescriprionIsNull() {
            addCriterion("shp_descriprion is null");
            return (Criteria) this;
        }

        public Criteria andShpDescriprionIsNotNull() {
            addCriterion("shp_descriprion is not null");
            return (Criteria) this;
        }

        public Criteria andShpDescriprionEqualTo(String value) {
            addCriterion("shp_descriprion =", value, "shpDescriprion");
            return (Criteria) this;
        }

        public Criteria andShpDescriprionNotEqualTo(String value) {
            addCriterion("shp_descriprion <>", value, "shpDescriprion");
            return (Criteria) this;
        }

        public Criteria andShpDescriprionGreaterThan(String value) {
            addCriterion("shp_descriprion >", value, "shpDescriprion");
            return (Criteria) this;
        }

        public Criteria andShpDescriprionGreaterThanOrEqualTo(String value) {
            addCriterion("shp_descriprion >=", value, "shpDescriprion");
            return (Criteria) this;
        }

        public Criteria andShpDescriprionLessThan(String value) {
            addCriterion("shp_descriprion <", value, "shpDescriprion");
            return (Criteria) this;
        }

        public Criteria andShpDescriprionLessThanOrEqualTo(String value) {
            addCriterion("shp_descriprion <=", value, "shpDescriprion");
            return (Criteria) this;
        }

        public Criteria andShpDescriprionLike(String value) {
            addCriterion("shp_descriprion like", value, "shpDescriprion");
            return (Criteria) this;
        }

        public Criteria andShpDescriprionNotLike(String value) {
            addCriterion("shp_descriprion not like", value, "shpDescriprion");
            return (Criteria) this;
        }

        public Criteria andShpDescriprionIn(List<String> values) {
            addCriterion("shp_descriprion in", values, "shpDescriprion");
            return (Criteria) this;
        }

        public Criteria andShpDescriprionNotIn(List<String> values) {
            addCriterion("shp_descriprion not in", values, "shpDescriprion");
            return (Criteria) this;
        }

        public Criteria andShpDescriprionBetween(String value1, String value2) {
            addCriterion("shp_descriprion between", value1, value2, "shpDescriprion");
            return (Criteria) this;
        }

        public Criteria andShpDescriprionNotBetween(String value1, String value2) {
            addCriterion("shp_descriprion not between", value1, value2, "shpDescriprion");
            return (Criteria) this;
        }

        public Criteria andShpLbIsNull() {
            addCriterion("shp_lb is null");
            return (Criteria) this;
        }

        public Criteria andShpLbIsNotNull() {
            addCriterion("shp_lb is not null");
            return (Criteria) this;
        }

        public Criteria andShpLbEqualTo(String value) {
            addCriterion("shp_lb =", value, "shpLb");
            return (Criteria) this;
        }

        public Criteria andShpLbNotEqualTo(String value) {
            addCriterion("shp_lb <>", value, "shpLb");
            return (Criteria) this;
        }

        public Criteria andShpLbGreaterThan(String value) {
            addCriterion("shp_lb >", value, "shpLb");
            return (Criteria) this;
        }

        public Criteria andShpLbGreaterThanOrEqualTo(String value) {
            addCriterion("shp_lb >=", value, "shpLb");
            return (Criteria) this;
        }

        public Criteria andShpLbLessThan(String value) {
            addCriterion("shp_lb <", value, "shpLb");
            return (Criteria) this;
        }

        public Criteria andShpLbLessThanOrEqualTo(String value) {
            addCriterion("shp_lb <=", value, "shpLb");
            return (Criteria) this;
        }

        public Criteria andShpLbLike(String value) {
            addCriterion("shp_lb like", value, "shpLb");
            return (Criteria) this;
        }

        public Criteria andShpLbNotLike(String value) {
            addCriterion("shp_lb not like", value, "shpLb");
            return (Criteria) this;
        }

        public Criteria andShpLbIn(List<String> values) {
            addCriterion("shp_lb in", values, "shpLb");
            return (Criteria) this;
        }

        public Criteria andShpLbNotIn(List<String> values) {
            addCriterion("shp_lb not in", values, "shpLb");
            return (Criteria) this;
        }

        public Criteria andShpLbBetween(String value1, String value2) {
            addCriterion("shp_lb between", value1, value2, "shpLb");
            return (Criteria) this;
        }

        public Criteria andShpLbNotBetween(String value1, String value2) {
            addCriterion("shp_lb not between", value1, value2, "shpLb");
            return (Criteria) this;
        }

        public Criteria andTradeIdIsNull() {
            addCriterion("trade_id is null");
            return (Criteria) this;
        }

        public Criteria andTradeIdIsNotNull() {
            addCriterion("trade_id is not null");
            return (Criteria) this;
        }

        public Criteria andTradeIdEqualTo(Integer value) {
            addCriterion("trade_id =", value, "tradeId");
            return (Criteria) this;
        }

        public Criteria andTradeIdNotEqualTo(Integer value) {
            addCriterion("trade_id <>", value, "tradeId");
            return (Criteria) this;
        }

        public Criteria andTradeIdGreaterThan(Integer value) {
            addCriterion("trade_id >", value, "tradeId");
            return (Criteria) this;
        }

        public Criteria andTradeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("trade_id >=", value, "tradeId");
            return (Criteria) this;
        }

        public Criteria andTradeIdLessThan(Integer value) {
            addCriterion("trade_id <", value, "tradeId");
            return (Criteria) this;
        }

        public Criteria andTradeIdLessThanOrEqualTo(Integer value) {
            addCriterion("trade_id <=", value, "tradeId");
            return (Criteria) this;
        }

        public Criteria andTradeIdIn(List<Integer> values) {
            addCriterion("trade_id in", values, "tradeId");
            return (Criteria) this;
        }

        public Criteria andTradeIdNotIn(List<Integer> values) {
            addCriterion("trade_id not in", values, "tradeId");
            return (Criteria) this;
        }

        public Criteria andTradeIdBetween(Integer value1, Integer value2) {
            addCriterion("trade_id between", value1, value2, "tradeId");
            return (Criteria) this;
        }

        public Criteria andTradeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("trade_id not between", value1, value2, "tradeId");
            return (Criteria) this;
        }

        public Criteria andShpzZhlIsNull() {
            addCriterion("shpz_zhl is null");
            return (Criteria) this;
        }

        public Criteria andShpzZhlIsNotNull() {
            addCriterion("shpz_zhl is not null");
            return (Criteria) this;
        }

        public Criteria andShpzZhlEqualTo(String value) {
            addCriterion("shpz_zhl =", value, "shpzZhl");
            return (Criteria) this;
        }

        public Criteria andShpzZhlNotEqualTo(String value) {
            addCriterion("shpz_zhl <>", value, "shpzZhl");
            return (Criteria) this;
        }

        public Criteria andShpzZhlGreaterThan(String value) {
            addCriterion("shpz_zhl >", value, "shpzZhl");
            return (Criteria) this;
        }

        public Criteria andShpzZhlGreaterThanOrEqualTo(String value) {
            addCriterion("shpz_zhl >=", value, "shpzZhl");
            return (Criteria) this;
        }

        public Criteria andShpzZhlLessThan(String value) {
            addCriterion("shpz_zhl <", value, "shpzZhl");
            return (Criteria) this;
        }

        public Criteria andShpzZhlLessThanOrEqualTo(String value) {
            addCriterion("shpz_zhl <=", value, "shpzZhl");
            return (Criteria) this;
        }

        public Criteria andShpzZhlLike(String value) {
            addCriterion("shpz_zhl like", value, "shpzZhl");
            return (Criteria) this;
        }

        public Criteria andShpzZhlNotLike(String value) {
            addCriterion("shpz_zhl not like", value, "shpzZhl");
            return (Criteria) this;
        }

        public Criteria andShpzZhlIn(List<String> values) {
            addCriterion("shpz_zhl in", values, "shpzZhl");
            return (Criteria) this;
        }

        public Criteria andShpzZhlNotIn(List<String> values) {
            addCriterion("shpz_zhl not in", values, "shpzZhl");
            return (Criteria) this;
        }

        public Criteria andShpzZhlBetween(String value1, String value2) {
            addCriterion("shpz_zhl between", value1, value2, "shpzZhl");
            return (Criteria) this;
        }

        public Criteria andShpzZhlNotBetween(String value1, String value2) {
            addCriterion("shpz_zhl not between", value1, value2, "shpzZhl");
            return (Criteria) this;
        }

        public Criteria andShpChcIsNull() {
            addCriterion("shp_chc is null");
            return (Criteria) this;
        }

        public Criteria andShpChcIsNotNull() {
            addCriterion("shp_chc is not null");
            return (Criteria) this;
        }

        public Criteria andShpChcEqualTo(String value) {
            addCriterion("shp_chc =", value, "shpChc");
            return (Criteria) this;
        }

        public Criteria andShpChcNotEqualTo(String value) {
            addCriterion("shp_chc <>", value, "shpChc");
            return (Criteria) this;
        }

        public Criteria andShpChcGreaterThan(String value) {
            addCriterion("shp_chc >", value, "shpChc");
            return (Criteria) this;
        }

        public Criteria andShpChcGreaterThanOrEqualTo(String value) {
            addCriterion("shp_chc >=", value, "shpChc");
            return (Criteria) this;
        }

        public Criteria andShpChcLessThan(String value) {
            addCriterion("shp_chc <", value, "shpChc");
            return (Criteria) this;
        }

        public Criteria andShpChcLessThanOrEqualTo(String value) {
            addCriterion("shp_chc <=", value, "shpChc");
            return (Criteria) this;
        }

        public Criteria andShpChcLike(String value) {
            addCriterion("shp_chc like", value, "shpChc");
            return (Criteria) this;
        }

        public Criteria andShpChcNotLike(String value) {
            addCriterion("shp_chc not like", value, "shpChc");
            return (Criteria) this;
        }

        public Criteria andShpChcIn(List<String> values) {
            addCriterion("shp_chc in", values, "shpChc");
            return (Criteria) this;
        }

        public Criteria andShpChcNotIn(List<String> values) {
            addCriterion("shp_chc not in", values, "shpChc");
            return (Criteria) this;
        }

        public Criteria andShpChcBetween(String value1, String value2) {
            addCriterion("shp_chc between", value1, value2, "shpChc");
            return (Criteria) this;
        }

        public Criteria andShpChcNotBetween(String value1, String value2) {
            addCriterion("shp_chc not between", value1, value2, "shpChc");
            return (Criteria) this;
        }

        public Criteria andChjTimeIsNull() {
            addCriterion("chj_time is null");
            return (Criteria) this;
        }

        public Criteria andChjTimeIsNotNull() {
            addCriterion("chj_time is not null");
            return (Criteria) this;
        }

        public Criteria andChjTimeEqualTo(Date value) {
            addCriterion("chj_time =", value, "chjTime");
            return (Criteria) this;
        }

        public Criteria andChjTimeNotEqualTo(Date value) {
            addCriterion("chj_time <>", value, "chjTime");
            return (Criteria) this;
        }

        public Criteria andChjTimeGreaterThan(Date value) {
            addCriterion("chj_time >", value, "chjTime");
            return (Criteria) this;
        }

        public Criteria andChjTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("chj_time >=", value, "chjTime");
            return (Criteria) this;
        }

        public Criteria andChjTimeLessThan(Date value) {
            addCriterion("chj_time <", value, "chjTime");
            return (Criteria) this;
        }

        public Criteria andChjTimeLessThanOrEqualTo(Date value) {
            addCriterion("chj_time <=", value, "chjTime");
            return (Criteria) this;
        }

        public Criteria andChjTimeIn(List<Date> values) {
            addCriterion("chj_time in", values, "chjTime");
            return (Criteria) this;
        }

        public Criteria andChjTimeNotIn(List<Date> values) {
            addCriterion("chj_time not in", values, "chjTime");
            return (Criteria) this;
        }

        public Criteria andChjTimeBetween(Date value1, Date value2) {
            addCriterion("chj_time between", value1, value2, "chjTime");
            return (Criteria) this;
        }

        public Criteria andChjTimeNotBetween(Date value1, Date value2) {
            addCriterion("chj_time not between", value1, value2, "chjTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 29 10:55:34 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}