package com.alpha.mall.manager.pojo;

public class TMallShoppingcarInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar_info.Id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar_info.sku_name
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Long skuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar_info.sku_price
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer skuPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar_info.user_xm
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String userXm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar_info.user_nch
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String userNch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar_info.user_dz
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String userDz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar_info.product_name
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar_info.shp_pic
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String shpPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar_info.sku_kc
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer skuKc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar_info.sku_shx
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String skuShx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar_info.Id
     *
     * @return the value of t_mall_shoppingcar_info.Id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar_info.Id
     *
     * @param id the value for t_mall_shoppingcar_info.Id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar_info.sku_name
     *
     * @return the value of t_mall_shoppingcar_info.sku_name
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Long getSkuName() {
        return skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar_info.sku_name
     *
     * @param skuName the value for t_mall_shoppingcar_info.sku_name
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setSkuName(Long skuName) {
        this.skuName = skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar_info.sku_price
     *
     * @return the value of t_mall_shoppingcar_info.sku_price
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getSkuPrice() {
        return skuPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar_info.sku_price
     *
     * @param skuPrice the value for t_mall_shoppingcar_info.sku_price
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setSkuPrice(Integer skuPrice) {
        this.skuPrice = skuPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar_info.user_xm
     *
     * @return the value of t_mall_shoppingcar_info.user_xm
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getUserXm() {
        return userXm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar_info.user_xm
     *
     * @param userXm the value for t_mall_shoppingcar_info.user_xm
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setUserXm(String userXm) {
        this.userXm = userXm == null ? null : userXm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar_info.user_nch
     *
     * @return the value of t_mall_shoppingcar_info.user_nch
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getUserNch() {
        return userNch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar_info.user_nch
     *
     * @param userNch the value for t_mall_shoppingcar_info.user_nch
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setUserNch(String userNch) {
        this.userNch = userNch == null ? null : userNch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar_info.user_dz
     *
     * @return the value of t_mall_shoppingcar_info.user_dz
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getUserDz() {
        return userDz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar_info.user_dz
     *
     * @param userDz the value for t_mall_shoppingcar_info.user_dz
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setUserDz(String userDz) {
        this.userDz = userDz == null ? null : userDz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar_info.product_name
     *
     * @return the value of t_mall_shoppingcar_info.product_name
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar_info.product_name
     *
     * @param productName the value for t_mall_shoppingcar_info.product_name
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar_info.shp_pic
     *
     * @return the value of t_mall_shoppingcar_info.shp_pic
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getShpPic() {
        return shpPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar_info.shp_pic
     *
     * @param shpPic the value for t_mall_shoppingcar_info.shp_pic
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setShpPic(String shpPic) {
        this.shpPic = shpPic == null ? null : shpPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar_info.sku_kc
     *
     * @return the value of t_mall_shoppingcar_info.sku_kc
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getSkuKc() {
        return skuKc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar_info.sku_kc
     *
     * @param skuKc the value for t_mall_shoppingcar_info.sku_kc
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setSkuKc(Integer skuKc) {
        this.skuKc = skuKc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar_info.sku_shx
     *
     * @return the value of t_mall_shoppingcar_info.sku_shx
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getSkuShx() {
        return skuShx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar_info.sku_shx
     *
     * @param skuShx the value for t_mall_shoppingcar_info.sku_shx
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setSkuShx(String skuShx) {
        this.skuShx = skuShx == null ? null : skuShx.trim();
    }
}