package com.alpha.mall.manager.pojo;

import java.util.ArrayList;
import java.util.List;

public class TMallShoppingcarInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public TMallShoppingcarInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSkuNameIsNull() {
            addCriterion("sku_name is null");
            return (Criteria) this;
        }

        public Criteria andSkuNameIsNotNull() {
            addCriterion("sku_name is not null");
            return (Criteria) this;
        }

        public Criteria andSkuNameEqualTo(Long value) {
            addCriterion("sku_name =", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotEqualTo(Long value) {
            addCriterion("sku_name <>", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameGreaterThan(Long value) {
            addCriterion("sku_name >", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameGreaterThanOrEqualTo(Long value) {
            addCriterion("sku_name >=", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLessThan(Long value) {
            addCriterion("sku_name <", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLessThanOrEqualTo(Long value) {
            addCriterion("sku_name <=", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameIn(List<Long> values) {
            addCriterion("sku_name in", values, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotIn(List<Long> values) {
            addCriterion("sku_name not in", values, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameBetween(Long value1, Long value2) {
            addCriterion("sku_name between", value1, value2, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotBetween(Long value1, Long value2) {
            addCriterion("sku_name not between", value1, value2, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuPriceIsNull() {
            addCriterion("sku_price is null");
            return (Criteria) this;
        }

        public Criteria andSkuPriceIsNotNull() {
            addCriterion("sku_price is not null");
            return (Criteria) this;
        }

        public Criteria andSkuPriceEqualTo(Integer value) {
            addCriterion("sku_price =", value, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceNotEqualTo(Integer value) {
            addCriterion("sku_price <>", value, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceGreaterThan(Integer value) {
            addCriterion("sku_price >", value, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("sku_price >=", value, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceLessThan(Integer value) {
            addCriterion("sku_price <", value, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceLessThanOrEqualTo(Integer value) {
            addCriterion("sku_price <=", value, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceIn(List<Integer> values) {
            addCriterion("sku_price in", values, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceNotIn(List<Integer> values) {
            addCriterion("sku_price not in", values, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceBetween(Integer value1, Integer value2) {
            addCriterion("sku_price between", value1, value2, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("sku_price not between", value1, value2, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andUserXmIsNull() {
            addCriterion("user_xm is null");
            return (Criteria) this;
        }

        public Criteria andUserXmIsNotNull() {
            addCriterion("user_xm is not null");
            return (Criteria) this;
        }

        public Criteria andUserXmEqualTo(String value) {
            addCriterion("user_xm =", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmNotEqualTo(String value) {
            addCriterion("user_xm <>", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmGreaterThan(String value) {
            addCriterion("user_xm >", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmGreaterThanOrEqualTo(String value) {
            addCriterion("user_xm >=", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmLessThan(String value) {
            addCriterion("user_xm <", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmLessThanOrEqualTo(String value) {
            addCriterion("user_xm <=", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmLike(String value) {
            addCriterion("user_xm like", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmNotLike(String value) {
            addCriterion("user_xm not like", value, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmIn(List<String> values) {
            addCriterion("user_xm in", values, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmNotIn(List<String> values) {
            addCriterion("user_xm not in", values, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmBetween(String value1, String value2) {
            addCriterion("user_xm between", value1, value2, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserXmNotBetween(String value1, String value2) {
            addCriterion("user_xm not between", value1, value2, "userXm");
            return (Criteria) this;
        }

        public Criteria andUserNchIsNull() {
            addCriterion("user_nch is null");
            return (Criteria) this;
        }

        public Criteria andUserNchIsNotNull() {
            addCriterion("user_nch is not null");
            return (Criteria) this;
        }

        public Criteria andUserNchEqualTo(String value) {
            addCriterion("user_nch =", value, "userNch");
            return (Criteria) this;
        }

        public Criteria andUserNchNotEqualTo(String value) {
            addCriterion("user_nch <>", value, "userNch");
            return (Criteria) this;
        }

        public Criteria andUserNchGreaterThan(String value) {
            addCriterion("user_nch >", value, "userNch");
            return (Criteria) this;
        }

        public Criteria andUserNchGreaterThanOrEqualTo(String value) {
            addCriterion("user_nch >=", value, "userNch");
            return (Criteria) this;
        }

        public Criteria andUserNchLessThan(String value) {
            addCriterion("user_nch <", value, "userNch");
            return (Criteria) this;
        }

        public Criteria andUserNchLessThanOrEqualTo(String value) {
            addCriterion("user_nch <=", value, "userNch");
            return (Criteria) this;
        }

        public Criteria andUserNchLike(String value) {
            addCriterion("user_nch like", value, "userNch");
            return (Criteria) this;
        }

        public Criteria andUserNchNotLike(String value) {
            addCriterion("user_nch not like", value, "userNch");
            return (Criteria) this;
        }

        public Criteria andUserNchIn(List<String> values) {
            addCriterion("user_nch in", values, "userNch");
            return (Criteria) this;
        }

        public Criteria andUserNchNotIn(List<String> values) {
            addCriterion("user_nch not in", values, "userNch");
            return (Criteria) this;
        }

        public Criteria andUserNchBetween(String value1, String value2) {
            addCriterion("user_nch between", value1, value2, "userNch");
            return (Criteria) this;
        }

        public Criteria andUserNchNotBetween(String value1, String value2) {
            addCriterion("user_nch not between", value1, value2, "userNch");
            return (Criteria) this;
        }

        public Criteria andUserDzIsNull() {
            addCriterion("user_dz is null");
            return (Criteria) this;
        }

        public Criteria andUserDzIsNotNull() {
            addCriterion("user_dz is not null");
            return (Criteria) this;
        }

        public Criteria andUserDzEqualTo(String value) {
            addCriterion("user_dz =", value, "userDz");
            return (Criteria) this;
        }

        public Criteria andUserDzNotEqualTo(String value) {
            addCriterion("user_dz <>", value, "userDz");
            return (Criteria) this;
        }

        public Criteria andUserDzGreaterThan(String value) {
            addCriterion("user_dz >", value, "userDz");
            return (Criteria) this;
        }

        public Criteria andUserDzGreaterThanOrEqualTo(String value) {
            addCriterion("user_dz >=", value, "userDz");
            return (Criteria) this;
        }

        public Criteria andUserDzLessThan(String value) {
            addCriterion("user_dz <", value, "userDz");
            return (Criteria) this;
        }

        public Criteria andUserDzLessThanOrEqualTo(String value) {
            addCriterion("user_dz <=", value, "userDz");
            return (Criteria) this;
        }

        public Criteria andUserDzLike(String value) {
            addCriterion("user_dz like", value, "userDz");
            return (Criteria) this;
        }

        public Criteria andUserDzNotLike(String value) {
            addCriterion("user_dz not like", value, "userDz");
            return (Criteria) this;
        }

        public Criteria andUserDzIn(List<String> values) {
            addCriterion("user_dz in", values, "userDz");
            return (Criteria) this;
        }

        public Criteria andUserDzNotIn(List<String> values) {
            addCriterion("user_dz not in", values, "userDz");
            return (Criteria) this;
        }

        public Criteria andUserDzBetween(String value1, String value2) {
            addCriterion("user_dz between", value1, value2, "userDz");
            return (Criteria) this;
        }

        public Criteria andUserDzNotBetween(String value1, String value2) {
            addCriterion("user_dz not between", value1, value2, "userDz");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andShpPicIsNull() {
            addCriterion("shp_pic is null");
            return (Criteria) this;
        }

        public Criteria andShpPicIsNotNull() {
            addCriterion("shp_pic is not null");
            return (Criteria) this;
        }

        public Criteria andShpPicEqualTo(String value) {
            addCriterion("shp_pic =", value, "shpPic");
            return (Criteria) this;
        }

        public Criteria andShpPicNotEqualTo(String value) {
            addCriterion("shp_pic <>", value, "shpPic");
            return (Criteria) this;
        }

        public Criteria andShpPicGreaterThan(String value) {
            addCriterion("shp_pic >", value, "shpPic");
            return (Criteria) this;
        }

        public Criteria andShpPicGreaterThanOrEqualTo(String value) {
            addCriterion("shp_pic >=", value, "shpPic");
            return (Criteria) this;
        }

        public Criteria andShpPicLessThan(String value) {
            addCriterion("shp_pic <", value, "shpPic");
            return (Criteria) this;
        }

        public Criteria andShpPicLessThanOrEqualTo(String value) {
            addCriterion("shp_pic <=", value, "shpPic");
            return (Criteria) this;
        }

        public Criteria andShpPicLike(String value) {
            addCriterion("shp_pic like", value, "shpPic");
            return (Criteria) this;
        }

        public Criteria andShpPicNotLike(String value) {
            addCriterion("shp_pic not like", value, "shpPic");
            return (Criteria) this;
        }

        public Criteria andShpPicIn(List<String> values) {
            addCriterion("shp_pic in", values, "shpPic");
            return (Criteria) this;
        }

        public Criteria andShpPicNotIn(List<String> values) {
            addCriterion("shp_pic not in", values, "shpPic");
            return (Criteria) this;
        }

        public Criteria andShpPicBetween(String value1, String value2) {
            addCriterion("shp_pic between", value1, value2, "shpPic");
            return (Criteria) this;
        }

        public Criteria andShpPicNotBetween(String value1, String value2) {
            addCriterion("shp_pic not between", value1, value2, "shpPic");
            return (Criteria) this;
        }

        public Criteria andSkuKcIsNull() {
            addCriterion("sku_kc is null");
            return (Criteria) this;
        }

        public Criteria andSkuKcIsNotNull() {
            addCriterion("sku_kc is not null");
            return (Criteria) this;
        }

        public Criteria andSkuKcEqualTo(Integer value) {
            addCriterion("sku_kc =", value, "skuKc");
            return (Criteria) this;
        }

        public Criteria andSkuKcNotEqualTo(Integer value) {
            addCriterion("sku_kc <>", value, "skuKc");
            return (Criteria) this;
        }

        public Criteria andSkuKcGreaterThan(Integer value) {
            addCriterion("sku_kc >", value, "skuKc");
            return (Criteria) this;
        }

        public Criteria andSkuKcGreaterThanOrEqualTo(Integer value) {
            addCriterion("sku_kc >=", value, "skuKc");
            return (Criteria) this;
        }

        public Criteria andSkuKcLessThan(Integer value) {
            addCriterion("sku_kc <", value, "skuKc");
            return (Criteria) this;
        }

        public Criteria andSkuKcLessThanOrEqualTo(Integer value) {
            addCriterion("sku_kc <=", value, "skuKc");
            return (Criteria) this;
        }

        public Criteria andSkuKcIn(List<Integer> values) {
            addCriterion("sku_kc in", values, "skuKc");
            return (Criteria) this;
        }

        public Criteria andSkuKcNotIn(List<Integer> values) {
            addCriterion("sku_kc not in", values, "skuKc");
            return (Criteria) this;
        }

        public Criteria andSkuKcBetween(Integer value1, Integer value2) {
            addCriterion("sku_kc between", value1, value2, "skuKc");
            return (Criteria) this;
        }

        public Criteria andSkuKcNotBetween(Integer value1, Integer value2) {
            addCriterion("sku_kc not between", value1, value2, "skuKc");
            return (Criteria) this;
        }

        public Criteria andSkuShxIsNull() {
            addCriterion("sku_shx is null");
            return (Criteria) this;
        }

        public Criteria andSkuShxIsNotNull() {
            addCriterion("sku_shx is not null");
            return (Criteria) this;
        }

        public Criteria andSkuShxEqualTo(String value) {
            addCriterion("sku_shx =", value, "skuShx");
            return (Criteria) this;
        }

        public Criteria andSkuShxNotEqualTo(String value) {
            addCriterion("sku_shx <>", value, "skuShx");
            return (Criteria) this;
        }

        public Criteria andSkuShxGreaterThan(String value) {
            addCriterion("sku_shx >", value, "skuShx");
            return (Criteria) this;
        }

        public Criteria andSkuShxGreaterThanOrEqualTo(String value) {
            addCriterion("sku_shx >=", value, "skuShx");
            return (Criteria) this;
        }

        public Criteria andSkuShxLessThan(String value) {
            addCriterion("sku_shx <", value, "skuShx");
            return (Criteria) this;
        }

        public Criteria andSkuShxLessThanOrEqualTo(String value) {
            addCriterion("sku_shx <=", value, "skuShx");
            return (Criteria) this;
        }

        public Criteria andSkuShxLike(String value) {
            addCriterion("sku_shx like", value, "skuShx");
            return (Criteria) this;
        }

        public Criteria andSkuShxNotLike(String value) {
            addCriterion("sku_shx not like", value, "skuShx");
            return (Criteria) this;
        }

        public Criteria andSkuShxIn(List<String> values) {
            addCriterion("sku_shx in", values, "skuShx");
            return (Criteria) this;
        }

        public Criteria andSkuShxNotIn(List<String> values) {
            addCriterion("sku_shx not in", values, "skuShx");
            return (Criteria) this;
        }

        public Criteria andSkuShxBetween(String value1, String value2) {
            addCriterion("sku_shx between", value1, value2, "skuShx");
            return (Criteria) this;
        }

        public Criteria andSkuShxNotBetween(String value1, String value2) {
            addCriterion("sku_shx not between", value1, value2, "skuShx");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 29 10:55:34 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}