package com.alpha.mall.manager.pojo;

public class TMallClass1 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_class_1.id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_class_1.flname1
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String flname1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_class_1.id
     *
     * @return the value of t_mall_class_1.id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_class_1.id
     *
     * @param id the value for t_mall_class_1.id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_class_1.flname1
     *
     * @return the value of t_mall_class_1.flname1
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getFlname1() {
        return flname1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_class_1.flname1
     *
     * @param flname1 the value for t_mall_class_1.flname1
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setFlname1(String flname1) {
        this.flname1 = flname1 == null ? null : flname1.trim();
    }
}