package com.alpha.mall.manager.pojo;

import java.util.Date;

public class TMallFlow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow.Id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow.psfsh
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private String psfsh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow.psshj
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private Date psshj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow.psmsh
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private String psmsh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow.yh_id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private Integer yhId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow.chjshj
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private Date chjshj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow.dd_id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private Integer ddId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow.mqdd
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private String mqdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow.mdd
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private String mdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow.ywy
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private String ywy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow.lxfsh
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private String lxfsh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow.Id
     *
     * @return the value of t_mall_flow.Id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow.Id
     *
     * @param id the value for t_mall_flow.Id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow.psfsh
     *
     * @return the value of t_mall_flow.psfsh
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public String getPsfsh() {
        return psfsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow.psfsh
     *
     * @param psfsh the value for t_mall_flow.psfsh
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setPsfsh(String psfsh) {
        this.psfsh = psfsh == null ? null : psfsh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow.psshj
     *
     * @return the value of t_mall_flow.psshj
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public Date getPsshj() {
        return psshj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow.psshj
     *
     * @param psshj the value for t_mall_flow.psshj
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setPsshj(Date psshj) {
        this.psshj = psshj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow.psmsh
     *
     * @return the value of t_mall_flow.psmsh
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public String getPsmsh() {
        return psmsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow.psmsh
     *
     * @param psmsh the value for t_mall_flow.psmsh
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setPsmsh(String psmsh) {
        this.psmsh = psmsh == null ? null : psmsh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow.yh_id
     *
     * @return the value of t_mall_flow.yh_id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public Integer getYhId() {
        return yhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow.yh_id
     *
     * @param yhId the value for t_mall_flow.yh_id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setYhId(Integer yhId) {
        this.yhId = yhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow.chjshj
     *
     * @return the value of t_mall_flow.chjshj
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public Date getChjshj() {
        return chjshj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow.chjshj
     *
     * @param chjshj the value for t_mall_flow.chjshj
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setChjshj(Date chjshj) {
        this.chjshj = chjshj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow.dd_id
     *
     * @return the value of t_mall_flow.dd_id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public Integer getDdId() {
        return ddId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow.dd_id
     *
     * @param ddId the value for t_mall_flow.dd_id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setDdId(Integer ddId) {
        this.ddId = ddId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow.mqdd
     *
     * @return the value of t_mall_flow.mqdd
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public String getMqdd() {
        return mqdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow.mqdd
     *
     * @param mqdd the value for t_mall_flow.mqdd
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setMqdd(String mqdd) {
        this.mqdd = mqdd == null ? null : mqdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow.mdd
     *
     * @return the value of t_mall_flow.mdd
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public String getMdd() {
        return mdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow.mdd
     *
     * @param mdd the value for t_mall_flow.mdd
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setMdd(String mdd) {
        this.mdd = mdd == null ? null : mdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow.ywy
     *
     * @return the value of t_mall_flow.ywy
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public String getYwy() {
        return ywy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow.ywy
     *
     * @param ywy the value for t_mall_flow.ywy
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setYwy(String ywy) {
        this.ywy = ywy == null ? null : ywy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow.lxfsh
     *
     * @return the value of t_mall_flow.lxfsh
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public String getLxfsh() {
        return lxfsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow.lxfsh
     *
     * @param lxfsh the value for t_mall_flow.lxfsh
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setLxfsh(String lxfsh) {
        this.lxfsh = lxfsh == null ? null : lxfsh.trim();
    }
}