package com.alpha.mall.manager.pojo;

import java.util.Date;

public class TMallProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product.id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product.product_name
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product.shp_pic
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String shpPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product.class1
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer class1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product.class2
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer class2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product.trade_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer tradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product.chj_time
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Date chjTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product.shp_descriprion
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String shpDescriprion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product.id
     *
     * @return the value of t_mall_product.id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product.id
     *
     * @param id the value for t_mall_product.id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product.product_name
     *
     * @return the value of t_mall_product.product_name
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product.product_name
     *
     * @param productName the value for t_mall_product.product_name
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product.shp_pic
     *
     * @return the value of t_mall_product.shp_pic
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getShpPic() {
        return shpPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product.shp_pic
     *
     * @param shpPic the value for t_mall_product.shp_pic
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setShpPic(String shpPic) {
        this.shpPic = shpPic == null ? null : shpPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product.class1
     *
     * @return the value of t_mall_product.class1
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getClass1() {
        return class1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product.class1
     *
     * @param class1 the value for t_mall_product.class1
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setClass1(Integer class1) {
        this.class1 = class1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product.class2
     *
     * @return the value of t_mall_product.class2
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getClass2() {
        return class2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product.class2
     *
     * @param class2 the value for t_mall_product.class2
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setClass2(Integer class2) {
        this.class2 = class2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product.trade_id
     *
     * @return the value of t_mall_product.trade_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product.trade_id
     *
     * @param tradeId the value for t_mall_product.trade_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setTradeId(Integer tradeId) {
        this.tradeId = tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product.chj_time
     *
     * @return the value of t_mall_product.chj_time
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Date getChjTime() {
        return chjTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product.chj_time
     *
     * @param chjTime the value for t_mall_product.chj_time
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setChjTime(Date chjTime) {
        this.chjTime = chjTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product.shp_descriprion
     *
     * @return the value of t_mall_product.shp_descriprion
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getShpDescriprion() {
        return shpDescriprion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product.shp_descriprion
     *
     * @param shpDescriprion the value for t_mall_product.shp_descriprion
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setShpDescriprion(String shpDescriprion) {
        this.shpDescriprion = shpDescriprion == null ? null : shpDescriprion.trim();
    }
}