package com.alpha.mall.manager.pojo;

public class TMallFlowInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow_info.Id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow_info.Id
     *
     * @return the value of t_mall_flow_info.Id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow_info.Id
     *
     * @param id the value for t_mall_flow_info.Id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }
}