package com.alpha.mall.manager.pojo;

import java.util.Date;

public class TMallProductSkuInfo extends TMallProductSkuInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_sku_info.sku_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_sku_info.shp_descriprion
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String shpDescriprion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_sku_info.shp_lb
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String shpLb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_sku_info.trade_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer tradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_sku_info.shpz_zhl
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String shpzZhl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_sku_info.shp_chc
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String shpChc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_sku_info.chj_time
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Date chjTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_sku_info.sku_id
     *
     * @return the value of t_mall_product_sku_info.sku_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_sku_info.sku_id
     *
     * @param skuId the value for t_mall_product_sku_info.sku_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_sku_info.shp_descriprion
     *
     * @return the value of t_mall_product_sku_info.shp_descriprion
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getShpDescriprion() {
        return shpDescriprion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_sku_info.shp_descriprion
     *
     * @param shpDescriprion the value for t_mall_product_sku_info.shp_descriprion
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setShpDescriprion(String shpDescriprion) {
        this.shpDescriprion = shpDescriprion == null ? null : shpDescriprion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_sku_info.shp_lb
     *
     * @return the value of t_mall_product_sku_info.shp_lb
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getShpLb() {
        return shpLb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_sku_info.shp_lb
     *
     * @param shpLb the value for t_mall_product_sku_info.shp_lb
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setShpLb(String shpLb) {
        this.shpLb = shpLb == null ? null : shpLb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_sku_info.trade_id
     *
     * @return the value of t_mall_product_sku_info.trade_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_sku_info.trade_id
     *
     * @param tradeId the value for t_mall_product_sku_info.trade_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setTradeId(Integer tradeId) {
        this.tradeId = tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_sku_info.shpz_zhl
     *
     * @return the value of t_mall_product_sku_info.shpz_zhl
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getShpzZhl() {
        return shpzZhl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_sku_info.shpz_zhl
     *
     * @param shpzZhl the value for t_mall_product_sku_info.shpz_zhl
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setShpzZhl(String shpzZhl) {
        this.shpzZhl = shpzZhl == null ? null : shpzZhl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_sku_info.shp_chc
     *
     * @return the value of t_mall_product_sku_info.shp_chc
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getShpChc() {
        return shpChc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_sku_info.shp_chc
     *
     * @param shpChc the value for t_mall_product_sku_info.shp_chc
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setShpChc(String shpChc) {
        this.shpChc = shpChc == null ? null : shpChc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_sku_info.chj_time
     *
     * @return the value of t_mall_product_sku_info.chj_time
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Date getChjTime() {
        return chjTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_sku_info.chj_time
     *
     * @param chjTime the value for t_mall_product_sku_info.chj_time
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setChjTime(Date chjTime) {
        this.chjTime = chjTime;
    }
}