package com.alpha.mall.manager.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TMallProductCommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public TMallProductCommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andYhIdIsNull() {
            addCriterion("yh_id is null");
            return (Criteria) this;
        }

        public Criteria andYhIdIsNotNull() {
            addCriterion("yh_id is not null");
            return (Criteria) this;
        }

        public Criteria andYhIdEqualTo(Integer value) {
            addCriterion("yh_id =", value, "yhId");
            return (Criteria) this;
        }

        public Criteria andYhIdNotEqualTo(Integer value) {
            addCriterion("yh_id <>", value, "yhId");
            return (Criteria) this;
        }

        public Criteria andYhIdGreaterThan(Integer value) {
            addCriterion("yh_id >", value, "yhId");
            return (Criteria) this;
        }

        public Criteria andYhIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("yh_id >=", value, "yhId");
            return (Criteria) this;
        }

        public Criteria andYhIdLessThan(Integer value) {
            addCriterion("yh_id <", value, "yhId");
            return (Criteria) this;
        }

        public Criteria andYhIdLessThanOrEqualTo(Integer value) {
            addCriterion("yh_id <=", value, "yhId");
            return (Criteria) this;
        }

        public Criteria andYhIdIn(List<Integer> values) {
            addCriterion("yh_id in", values, "yhId");
            return (Criteria) this;
        }

        public Criteria andYhIdNotIn(List<Integer> values) {
            addCriterion("yh_id not in", values, "yhId");
            return (Criteria) this;
        }

        public Criteria andYhIdBetween(Integer value1, Integer value2) {
            addCriterion("yh_id between", value1, value2, "yhId");
            return (Criteria) this;
        }

        public Criteria andYhIdNotBetween(Integer value1, Integer value2) {
            addCriterion("yh_id not between", value1, value2, "yhId");
            return (Criteria) this;
        }

        public Criteria andPlnrIsNull() {
            addCriterion("plnr is null");
            return (Criteria) this;
        }

        public Criteria andPlnrIsNotNull() {
            addCriterion("plnr is not null");
            return (Criteria) this;
        }

        public Criteria andPlnrEqualTo(String value) {
            addCriterion("plnr =", value, "plnr");
            return (Criteria) this;
        }

        public Criteria andPlnrNotEqualTo(String value) {
            addCriterion("plnr <>", value, "plnr");
            return (Criteria) this;
        }

        public Criteria andPlnrGreaterThan(String value) {
            addCriterion("plnr >", value, "plnr");
            return (Criteria) this;
        }

        public Criteria andPlnrGreaterThanOrEqualTo(String value) {
            addCriterion("plnr >=", value, "plnr");
            return (Criteria) this;
        }

        public Criteria andPlnrLessThan(String value) {
            addCriterion("plnr <", value, "plnr");
            return (Criteria) this;
        }

        public Criteria andPlnrLessThanOrEqualTo(String value) {
            addCriterion("plnr <=", value, "plnr");
            return (Criteria) this;
        }

        public Criteria andPlnrLike(String value) {
            addCriterion("plnr like", value, "plnr");
            return (Criteria) this;
        }

        public Criteria andPlnrNotLike(String value) {
            addCriterion("plnr not like", value, "plnr");
            return (Criteria) this;
        }

        public Criteria andPlnrIn(List<String> values) {
            addCriterion("plnr in", values, "plnr");
            return (Criteria) this;
        }

        public Criteria andPlnrNotIn(List<String> values) {
            addCriterion("plnr not in", values, "plnr");
            return (Criteria) this;
        }

        public Criteria andPlnrBetween(String value1, String value2) {
            addCriterion("plnr between", value1, value2, "plnr");
            return (Criteria) this;
        }

        public Criteria andPlnrNotBetween(String value1, String value2) {
            addCriterion("plnr not between", value1, value2, "plnr");
            return (Criteria) this;
        }

        public Criteria andPlshjIsNull() {
            addCriterion("plshj is null");
            return (Criteria) this;
        }

        public Criteria andPlshjIsNotNull() {
            addCriterion("plshj is not null");
            return (Criteria) this;
        }

        public Criteria andPlshjEqualTo(Date value) {
            addCriterion("plshj =", value, "plshj");
            return (Criteria) this;
        }

        public Criteria andPlshjNotEqualTo(Date value) {
            addCriterion("plshj <>", value, "plshj");
            return (Criteria) this;
        }

        public Criteria andPlshjGreaterThan(Date value) {
            addCriterion("plshj >", value, "plshj");
            return (Criteria) this;
        }

        public Criteria andPlshjGreaterThanOrEqualTo(Date value) {
            addCriterion("plshj >=", value, "plshj");
            return (Criteria) this;
        }

        public Criteria andPlshjLessThan(Date value) {
            addCriterion("plshj <", value, "plshj");
            return (Criteria) this;
        }

        public Criteria andPlshjLessThanOrEqualTo(Date value) {
            addCriterion("plshj <=", value, "plshj");
            return (Criteria) this;
        }

        public Criteria andPlshjIn(List<Date> values) {
            addCriterion("plshj in", values, "plshj");
            return (Criteria) this;
        }

        public Criteria andPlshjNotIn(List<Date> values) {
            addCriterion("plshj not in", values, "plshj");
            return (Criteria) this;
        }

        public Criteria andPlshjBetween(Date value1, Date value2) {
            addCriterion("plshj between", value1, value2, "plshj");
            return (Criteria) this;
        }

        public Criteria andPlshjNotBetween(Date value1, Date value2) {
            addCriterion("plshj not between", value1, value2, "plshj");
            return (Criteria) this;
        }

        public Criteria andHpjbIsNull() {
            addCriterion("hpjb is null");
            return (Criteria) this;
        }

        public Criteria andHpjbIsNotNull() {
            addCriterion("hpjb is not null");
            return (Criteria) this;
        }

        public Criteria andHpjbEqualTo(Integer value) {
            addCriterion("hpjb =", value, "hpjb");
            return (Criteria) this;
        }

        public Criteria andHpjbNotEqualTo(Integer value) {
            addCriterion("hpjb <>", value, "hpjb");
            return (Criteria) this;
        }

        public Criteria andHpjbGreaterThan(Integer value) {
            addCriterion("hpjb >", value, "hpjb");
            return (Criteria) this;
        }

        public Criteria andHpjbGreaterThanOrEqualTo(Integer value) {
            addCriterion("hpjb >=", value, "hpjb");
            return (Criteria) this;
        }

        public Criteria andHpjbLessThan(Integer value) {
            addCriterion("hpjb <", value, "hpjb");
            return (Criteria) this;
        }

        public Criteria andHpjbLessThanOrEqualTo(Integer value) {
            addCriterion("hpjb <=", value, "hpjb");
            return (Criteria) this;
        }

        public Criteria andHpjbIn(List<Integer> values) {
            addCriterion("hpjb in", values, "hpjb");
            return (Criteria) this;
        }

        public Criteria andHpjbNotIn(List<Integer> values) {
            addCriterion("hpjb not in", values, "hpjb");
            return (Criteria) this;
        }

        public Criteria andHpjbBetween(Integer value1, Integer value2) {
            addCriterion("hpjb between", value1, value2, "hpjb");
            return (Criteria) this;
        }

        public Criteria andHpjbNotBetween(Integer value1, Integer value2) {
            addCriterion("hpjb not between", value1, value2, "hpjb");
            return (Criteria) this;
        }

        public Criteria andSkuIdIsNull() {
            addCriterion("sku_id is null");
            return (Criteria) this;
        }

        public Criteria andSkuIdIsNotNull() {
            addCriterion("sku_id is not null");
            return (Criteria) this;
        }

        public Criteria andSkuIdEqualTo(Integer value) {
            addCriterion("sku_id =", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotEqualTo(Integer value) {
            addCriterion("sku_id <>", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdGreaterThan(Integer value) {
            addCriterion("sku_id >", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sku_id >=", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLessThan(Integer value) {
            addCriterion("sku_id <", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLessThanOrEqualTo(Integer value) {
            addCriterion("sku_id <=", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdIn(List<Integer> values) {
            addCriterion("sku_id in", values, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotIn(List<Integer> values) {
            addCriterion("sku_id not in", values, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdBetween(Integer value1, Integer value2) {
            addCriterion("sku_id between", value1, value2, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sku_id not between", value1, value2, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuMchIsNull() {
            addCriterion("sku_mch is null");
            return (Criteria) this;
        }

        public Criteria andSkuMchIsNotNull() {
            addCriterion("sku_mch is not null");
            return (Criteria) this;
        }

        public Criteria andSkuMchEqualTo(String value) {
            addCriterion("sku_mch =", value, "skuMch");
            return (Criteria) this;
        }

        public Criteria andSkuMchNotEqualTo(String value) {
            addCriterion("sku_mch <>", value, "skuMch");
            return (Criteria) this;
        }

        public Criteria andSkuMchGreaterThan(String value) {
            addCriterion("sku_mch >", value, "skuMch");
            return (Criteria) this;
        }

        public Criteria andSkuMchGreaterThanOrEqualTo(String value) {
            addCriterion("sku_mch >=", value, "skuMch");
            return (Criteria) this;
        }

        public Criteria andSkuMchLessThan(String value) {
            addCriterion("sku_mch <", value, "skuMch");
            return (Criteria) this;
        }

        public Criteria andSkuMchLessThanOrEqualTo(String value) {
            addCriterion("sku_mch <=", value, "skuMch");
            return (Criteria) this;
        }

        public Criteria andSkuMchLike(String value) {
            addCriterion("sku_mch like", value, "skuMch");
            return (Criteria) this;
        }

        public Criteria andSkuMchNotLike(String value) {
            addCriterion("sku_mch not like", value, "skuMch");
            return (Criteria) this;
        }

        public Criteria andSkuMchIn(List<String> values) {
            addCriterion("sku_mch in", values, "skuMch");
            return (Criteria) this;
        }

        public Criteria andSkuMchNotIn(List<String> values) {
            addCriterion("sku_mch not in", values, "skuMch");
            return (Criteria) this;
        }

        public Criteria andSkuMchBetween(String value1, String value2) {
            addCriterion("sku_mch between", value1, value2, "skuMch");
            return (Criteria) this;
        }

        public Criteria andSkuMchNotBetween(String value1, String value2) {
            addCriterion("sku_mch not between", value1, value2, "skuMch");
            return (Criteria) this;
        }

        public Criteria andShpIdIsNull() {
            addCriterion("shp_id is null");
            return (Criteria) this;
        }

        public Criteria andShpIdIsNotNull() {
            addCriterion("shp_id is not null");
            return (Criteria) this;
        }

        public Criteria andShpIdEqualTo(Integer value) {
            addCriterion("shp_id =", value, "shpId");
            return (Criteria) this;
        }

        public Criteria andShpIdNotEqualTo(Integer value) {
            addCriterion("shp_id <>", value, "shpId");
            return (Criteria) this;
        }

        public Criteria andShpIdGreaterThan(Integer value) {
            addCriterion("shp_id >", value, "shpId");
            return (Criteria) this;
        }

        public Criteria andShpIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("shp_id >=", value, "shpId");
            return (Criteria) this;
        }

        public Criteria andShpIdLessThan(Integer value) {
            addCriterion("shp_id <", value, "shpId");
            return (Criteria) this;
        }

        public Criteria andShpIdLessThanOrEqualTo(Integer value) {
            addCriterion("shp_id <=", value, "shpId");
            return (Criteria) this;
        }

        public Criteria andShpIdIn(List<Integer> values) {
            addCriterion("shp_id in", values, "shpId");
            return (Criteria) this;
        }

        public Criteria andShpIdNotIn(List<Integer> values) {
            addCriterion("shp_id not in", values, "shpId");
            return (Criteria) this;
        }

        public Criteria andShpIdBetween(Integer value1, Integer value2) {
            addCriterion("shp_id between", value1, value2, "shpId");
            return (Criteria) this;
        }

        public Criteria andShpIdNotBetween(Integer value1, Integer value2) {
            addCriterion("shp_id not between", value1, value2, "shpId");
            return (Criteria) this;
        }

        public Criteria andShpMchIsNull() {
            addCriterion("shp_mch is null");
            return (Criteria) this;
        }

        public Criteria andShpMchIsNotNull() {
            addCriterion("shp_mch is not null");
            return (Criteria) this;
        }

        public Criteria andShpMchEqualTo(String value) {
            addCriterion("shp_mch =", value, "shpMch");
            return (Criteria) this;
        }

        public Criteria andShpMchNotEqualTo(String value) {
            addCriterion("shp_mch <>", value, "shpMch");
            return (Criteria) this;
        }

        public Criteria andShpMchGreaterThan(String value) {
            addCriterion("shp_mch >", value, "shpMch");
            return (Criteria) this;
        }

        public Criteria andShpMchGreaterThanOrEqualTo(String value) {
            addCriterion("shp_mch >=", value, "shpMch");
            return (Criteria) this;
        }

        public Criteria andShpMchLessThan(String value) {
            addCriterion("shp_mch <", value, "shpMch");
            return (Criteria) this;
        }

        public Criteria andShpMchLessThanOrEqualTo(String value) {
            addCriterion("shp_mch <=", value, "shpMch");
            return (Criteria) this;
        }

        public Criteria andShpMchLike(String value) {
            addCriterion("shp_mch like", value, "shpMch");
            return (Criteria) this;
        }

        public Criteria andShpMchNotLike(String value) {
            addCriterion("shp_mch not like", value, "shpMch");
            return (Criteria) this;
        }

        public Criteria andShpMchIn(List<String> values) {
            addCriterion("shp_mch in", values, "shpMch");
            return (Criteria) this;
        }

        public Criteria andShpMchNotIn(List<String> values) {
            addCriterion("shp_mch not in", values, "shpMch");
            return (Criteria) this;
        }

        public Criteria andShpMchBetween(String value1, String value2) {
            addCriterion("shp_mch between", value1, value2, "shpMch");
            return (Criteria) this;
        }

        public Criteria andShpMchNotBetween(String value1, String value2) {
            addCriterion("shp_mch not between", value1, value2, "shpMch");
            return (Criteria) this;
        }

        public Criteria andDdIdIsNull() {
            addCriterion("dd_id is null");
            return (Criteria) this;
        }

        public Criteria andDdIdIsNotNull() {
            addCriterion("dd_id is not null");
            return (Criteria) this;
        }

        public Criteria andDdIdEqualTo(Integer value) {
            addCriterion("dd_id =", value, "ddId");
            return (Criteria) this;
        }

        public Criteria andDdIdNotEqualTo(Integer value) {
            addCriterion("dd_id <>", value, "ddId");
            return (Criteria) this;
        }

        public Criteria andDdIdGreaterThan(Integer value) {
            addCriterion("dd_id >", value, "ddId");
            return (Criteria) this;
        }

        public Criteria andDdIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("dd_id >=", value, "ddId");
            return (Criteria) this;
        }

        public Criteria andDdIdLessThan(Integer value) {
            addCriterion("dd_id <", value, "ddId");
            return (Criteria) this;
        }

        public Criteria andDdIdLessThanOrEqualTo(Integer value) {
            addCriterion("dd_id <=", value, "ddId");
            return (Criteria) this;
        }

        public Criteria andDdIdIn(List<Integer> values) {
            addCriterion("dd_id in", values, "ddId");
            return (Criteria) this;
        }

        public Criteria andDdIdNotIn(List<Integer> values) {
            addCriterion("dd_id not in", values, "ddId");
            return (Criteria) this;
        }

        public Criteria andDdIdBetween(Integer value1, Integer value2) {
            addCriterion("dd_id between", value1, value2, "ddId");
            return (Criteria) this;
        }

        public Criteria andDdIdNotBetween(Integer value1, Integer value2) {
            addCriterion("dd_id not between", value1, value2, "ddId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated do_not_delete_during_merge Thu Jan 25 17:08:30 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}