package com.alpha.mall.manager.pojo;

import java.util.Date;

public class TMallProductSkuInfo extends TMallProductSkuInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_sku_info.sku_id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private Integer skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_sku_info.shp_msh
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private String shpMsh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_sku_info.shp_lb
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private String shpLb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_sku_info.pp_id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private Integer ppId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_sku_info.shpz_zhl
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private Double shpzZhl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_sku_info.shp_chc
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private Double shpChc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_sku_info.chjshj
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private Date chjshj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_sku_info.sku_id
     *
     * @return the value of t_mall_product_sku_info.sku_id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_sku_info.sku_id
     *
     * @param skuId the value for t_mall_product_sku_info.sku_id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_sku_info.shp_msh
     *
     * @return the value of t_mall_product_sku_info.shp_msh
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public String getShpMsh() {
        return shpMsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_sku_info.shp_msh
     *
     * @param shpMsh the value for t_mall_product_sku_info.shp_msh
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setShpMsh(String shpMsh) {
        this.shpMsh = shpMsh == null ? null : shpMsh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_sku_info.shp_lb
     *
     * @return the value of t_mall_product_sku_info.shp_lb
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public String getShpLb() {
        return shpLb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_sku_info.shp_lb
     *
     * @param shpLb the value for t_mall_product_sku_info.shp_lb
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setShpLb(String shpLb) {
        this.shpLb = shpLb == null ? null : shpLb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_sku_info.pp_id
     *
     * @return the value of t_mall_product_sku_info.pp_id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public Integer getPpId() {
        return ppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_sku_info.pp_id
     *
     * @param ppId the value for t_mall_product_sku_info.pp_id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setPpId(Integer ppId) {
        this.ppId = ppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_sku_info.shpz_zhl
     *
     * @return the value of t_mall_product_sku_info.shpz_zhl
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public Double getShpzZhl() {
        return shpzZhl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_sku_info.shpz_zhl
     *
     * @param shpzZhl the value for t_mall_product_sku_info.shpz_zhl
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setShpzZhl(Double shpzZhl) {
        this.shpzZhl = shpzZhl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_sku_info.shp_chc
     *
     * @return the value of t_mall_product_sku_info.shp_chc
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public Double getShpChc() {
        return shpChc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_sku_info.shp_chc
     *
     * @param shpChc the value for t_mall_product_sku_info.shp_chc
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setShpChc(Double shpChc) {
        this.shpChc = shpChc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_sku_info.chjshj
     *
     * @return the value of t_mall_product_sku_info.chjshj
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public Date getChjshj() {
        return chjshj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_sku_info.chjshj
     *
     * @param chjshj the value for t_mall_product_sku_info.chjshj
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setChjshj(Date chjshj) {
        this.chjshj = chjshj;
    }
}