package com.alpha.mall.manager.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TMallSku {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku.Id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku.shp_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer shpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku.kc
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer kc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku.price
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku.chj_time
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Date chjTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku.sku_name
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String skuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku.sku_xl
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer skuXl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku.kcdz
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String kcdz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku.Id
     *
     * @return the value of t_mall_sku.Id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku.Id
     *
     * @param id the value for t_mall_sku.Id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku.shp_id
     *
     * @return the value of t_mall_sku.shp_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getShpId() {
        return shpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku.shp_id
     *
     * @param shpId the value for t_mall_sku.shp_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setShpId(Integer shpId) {
        this.shpId = shpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku.kc
     *
     * @return the value of t_mall_sku.kc
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getKc() {
        return kc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku.kc
     *
     * @param kc the value for t_mall_sku.kc
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setKc(Integer kc) {
        this.kc = kc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku.price
     *
     * @return the value of t_mall_sku.price
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku.price
     *
     * @param price the value for t_mall_sku.price
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku.chj_time
     *
     * @return the value of t_mall_sku.chj_time
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Date getChjTime() {
        return chjTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku.chj_time
     *
     * @param chjTime the value for t_mall_sku.chj_time
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setChjTime(Date chjTime) {
        this.chjTime = chjTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku.sku_name
     *
     * @return the value of t_mall_sku.sku_name
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getSkuName() {
        return skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku.sku_name
     *
     * @param skuName the value for t_mall_sku.sku_name
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setSkuName(String skuName) {
        this.skuName = skuName == null ? null : skuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku.sku_xl
     *
     * @return the value of t_mall_sku.sku_xl
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getSkuXl() {
        return skuXl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku.sku_xl
     *
     * @param skuXl the value for t_mall_sku.sku_xl
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setSkuXl(Integer skuXl) {
        this.skuXl = skuXl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku.kcdz
     *
     * @return the value of t_mall_sku.kcdz
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getKcdz() {
        return kcdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku.kcdz
     *
     * @param kcdz the value for t_mall_sku.kcdz
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setKcdz(String kcdz) {
        this.kcdz = kcdz == null ? null : kcdz.trim();
    }
}