package com.alpha.mall.manager.pojo;

public class TMallClass2 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_class_2.Id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_class_2.flmch2
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private String flmch2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_class_2.flbh1
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    private Integer flbh1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_class_2.Id
     *
     * @return the value of t_mall_class_2.Id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_class_2.Id
     *
     * @param id the value for t_mall_class_2.Id
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_class_2.flmch2
     *
     * @return the value of t_mall_class_2.flmch2
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public String getFlmch2() {
        return flmch2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_class_2.flmch2
     *
     * @param flmch2 the value for t_mall_class_2.flmch2
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setFlmch2(String flmch2) {
        this.flmch2 = flmch2 == null ? null : flmch2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_class_2.flbh1
     *
     * @return the value of t_mall_class_2.flbh1
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public Integer getFlbh1() {
        return flbh1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_class_2.flbh1
     *
     * @param flbh1 the value for t_mall_class_2.flbh1
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    public void setFlbh1(Integer flbh1) {
        this.flbh1 = flbh1;
    }
}