package com.alpha.mall.manager.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TMallUserPayExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mall_user_pay
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mall_user_pay
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mall_user_pay
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_user_pay
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public TMallUserPayExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_user_pay
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_user_pay
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_user_pay
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_user_pay
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_user_pay
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_user_pay
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_user_pay
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_user_pay
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_user_pay
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_user_pay
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mall_user_pay
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andDdIdIsNull() {
            addCriterion("dd_id is null");
            return (Criteria) this;
        }

        public Criteria andDdIdIsNotNull() {
            addCriterion("dd_id is not null");
            return (Criteria) this;
        }

        public Criteria andDdIdEqualTo(Integer value) {
            addCriterion("dd_id =", value, "ddId");
            return (Criteria) this;
        }

        public Criteria andDdIdNotEqualTo(Integer value) {
            addCriterion("dd_id <>", value, "ddId");
            return (Criteria) this;
        }

        public Criteria andDdIdGreaterThan(Integer value) {
            addCriterion("dd_id >", value, "ddId");
            return (Criteria) this;
        }

        public Criteria andDdIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("dd_id >=", value, "ddId");
            return (Criteria) this;
        }

        public Criteria andDdIdLessThan(Integer value) {
            addCriterion("dd_id <", value, "ddId");
            return (Criteria) this;
        }

        public Criteria andDdIdLessThanOrEqualTo(Integer value) {
            addCriterion("dd_id <=", value, "ddId");
            return (Criteria) this;
        }

        public Criteria andDdIdIn(List<Integer> values) {
            addCriterion("dd_id in", values, "ddId");
            return (Criteria) this;
        }

        public Criteria andDdIdNotIn(List<Integer> values) {
            addCriterion("dd_id not in", values, "ddId");
            return (Criteria) this;
        }

        public Criteria andDdIdBetween(Integer value1, Integer value2) {
            addCriterion("dd_id between", value1, value2, "ddId");
            return (Criteria) this;
        }

        public Criteria andDdIdNotBetween(Integer value1, Integer value2) {
            addCriterion("dd_id not between", value1, value2, "ddId");
            return (Criteria) this;
        }

        public Criteria andFkshjIsNull() {
            addCriterion("fkshj is null");
            return (Criteria) this;
        }

        public Criteria andFkshjIsNotNull() {
            addCriterion("fkshj is not null");
            return (Criteria) this;
        }

        public Criteria andFkshjEqualTo(Date value) {
            addCriterion("fkshj =", value, "fkshj");
            return (Criteria) this;
        }

        public Criteria andFkshjNotEqualTo(Date value) {
            addCriterion("fkshj <>", value, "fkshj");
            return (Criteria) this;
        }

        public Criteria andFkshjGreaterThan(Date value) {
            addCriterion("fkshj >", value, "fkshj");
            return (Criteria) this;
        }

        public Criteria andFkshjGreaterThanOrEqualTo(Date value) {
            addCriterion("fkshj >=", value, "fkshj");
            return (Criteria) this;
        }

        public Criteria andFkshjLessThan(Date value) {
            addCriterion("fkshj <", value, "fkshj");
            return (Criteria) this;
        }

        public Criteria andFkshjLessThanOrEqualTo(Date value) {
            addCriterion("fkshj <=", value, "fkshj");
            return (Criteria) this;
        }

        public Criteria andFkshjIn(List<Date> values) {
            addCriterion("fkshj in", values, "fkshj");
            return (Criteria) this;
        }

        public Criteria andFkshjNotIn(List<Date> values) {
            addCriterion("fkshj not in", values, "fkshj");
            return (Criteria) this;
        }

        public Criteria andFkshjBetween(Date value1, Date value2) {
            addCriterion("fkshj between", value1, value2, "fkshj");
            return (Criteria) this;
        }

        public Criteria andFkshjNotBetween(Date value1, Date value2) {
            addCriterion("fkshj not between", value1, value2, "fkshj");
            return (Criteria) this;
        }

        public Criteria andDdJeIsNull() {
            addCriterion("dd_je is null");
            return (Criteria) this;
        }

        public Criteria andDdJeIsNotNull() {
            addCriterion("dd_je is not null");
            return (Criteria) this;
        }

        public Criteria andDdJeEqualTo(Long value) {
            addCriterion("dd_je =", value, "ddJe");
            return (Criteria) this;
        }

        public Criteria andDdJeNotEqualTo(Long value) {
            addCriterion("dd_je <>", value, "ddJe");
            return (Criteria) this;
        }

        public Criteria andDdJeGreaterThan(Long value) {
            addCriterion("dd_je >", value, "ddJe");
            return (Criteria) this;
        }

        public Criteria andDdJeGreaterThanOrEqualTo(Long value) {
            addCriterion("dd_je >=", value, "ddJe");
            return (Criteria) this;
        }

        public Criteria andDdJeLessThan(Long value) {
            addCriterion("dd_je <", value, "ddJe");
            return (Criteria) this;
        }

        public Criteria andDdJeLessThanOrEqualTo(Long value) {
            addCriterion("dd_je <=", value, "ddJe");
            return (Criteria) this;
        }

        public Criteria andDdJeIn(List<Long> values) {
            addCriterion("dd_je in", values, "ddJe");
            return (Criteria) this;
        }

        public Criteria andDdJeNotIn(List<Long> values) {
            addCriterion("dd_je not in", values, "ddJe");
            return (Criteria) this;
        }

        public Criteria andDdJeBetween(Long value1, Long value2) {
            addCriterion("dd_je between", value1, value2, "ddJe");
            return (Criteria) this;
        }

        public Criteria andDdJeNotBetween(Long value1, Long value2) {
            addCriterion("dd_je not between", value1, value2, "ddJe");
            return (Criteria) this;
        }

        public Criteria andZhfModeIsNull() {
            addCriterion("zhf_mode is null");
            return (Criteria) this;
        }

        public Criteria andZhfModeIsNotNull() {
            addCriterion("zhf_mode is not null");
            return (Criteria) this;
        }

        public Criteria andZhfModeEqualTo(String value) {
            addCriterion("zhf_mode =", value, "zhfMode");
            return (Criteria) this;
        }

        public Criteria andZhfModeNotEqualTo(String value) {
            addCriterion("zhf_mode <>", value, "zhfMode");
            return (Criteria) this;
        }

        public Criteria andZhfModeGreaterThan(String value) {
            addCriterion("zhf_mode >", value, "zhfMode");
            return (Criteria) this;
        }

        public Criteria andZhfModeGreaterThanOrEqualTo(String value) {
            addCriterion("zhf_mode >=", value, "zhfMode");
            return (Criteria) this;
        }

        public Criteria andZhfModeLessThan(String value) {
            addCriterion("zhf_mode <", value, "zhfMode");
            return (Criteria) this;
        }

        public Criteria andZhfModeLessThanOrEqualTo(String value) {
            addCriterion("zhf_mode <=", value, "zhfMode");
            return (Criteria) this;
        }

        public Criteria andZhfModeLike(String value) {
            addCriterion("zhf_mode like", value, "zhfMode");
            return (Criteria) this;
        }

        public Criteria andZhfModeNotLike(String value) {
            addCriterion("zhf_mode not like", value, "zhfMode");
            return (Criteria) this;
        }

        public Criteria andZhfModeIn(List<String> values) {
            addCriterion("zhf_mode in", values, "zhfMode");
            return (Criteria) this;
        }

        public Criteria andZhfModeNotIn(List<String> values) {
            addCriterion("zhf_mode not in", values, "zhfMode");
            return (Criteria) this;
        }

        public Criteria andZhfModeBetween(String value1, String value2) {
            addCriterion("zhf_mode between", value1, value2, "zhfMode");
            return (Criteria) this;
        }

        public Criteria andZhfModeNotBetween(String value1, String value2) {
            addCriterion("zhf_mode not between", value1, value2, "zhfMode");
            return (Criteria) this;
        }

        public Criteria andBankIsNull() {
            addCriterion("bank is null");
            return (Criteria) this;
        }

        public Criteria andBankIsNotNull() {
            addCriterion("bank is not null");
            return (Criteria) this;
        }

        public Criteria andBankEqualTo(String value) {
            addCriterion("bank =", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotEqualTo(String value) {
            addCriterion("bank <>", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankGreaterThan(String value) {
            addCriterion("bank >", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankGreaterThanOrEqualTo(String value) {
            addCriterion("bank >=", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankLessThan(String value) {
            addCriterion("bank <", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankLessThanOrEqualTo(String value) {
            addCriterion("bank <=", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankLike(String value) {
            addCriterion("bank like", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotLike(String value) {
            addCriterion("bank not like", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankIn(List<String> values) {
            addCriterion("bank in", values, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotIn(List<String> values) {
            addCriterion("bank not in", values, "bank");
            return (Criteria) this;
        }

        public Criteria andBankBetween(String value1, String value2) {
            addCriterion("bank between", value1, value2, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotBetween(String value1, String value2) {
            addCriterion("bank not between", value1, value2, "bank");
            return (Criteria) this;
        }

        public Criteria andBankStatementIsNull() {
            addCriterion("bank_statement is null");
            return (Criteria) this;
        }

        public Criteria andBankStatementIsNotNull() {
            addCriterion("bank_statement is not null");
            return (Criteria) this;
        }

        public Criteria andBankStatementEqualTo(String value) {
            addCriterion("bank_statement =", value, "bankStatement");
            return (Criteria) this;
        }

        public Criteria andBankStatementNotEqualTo(String value) {
            addCriterion("bank_statement <>", value, "bankStatement");
            return (Criteria) this;
        }

        public Criteria andBankStatementGreaterThan(String value) {
            addCriterion("bank_statement >", value, "bankStatement");
            return (Criteria) this;
        }

        public Criteria andBankStatementGreaterThanOrEqualTo(String value) {
            addCriterion("bank_statement >=", value, "bankStatement");
            return (Criteria) this;
        }

        public Criteria andBankStatementLessThan(String value) {
            addCriterion("bank_statement <", value, "bankStatement");
            return (Criteria) this;
        }

        public Criteria andBankStatementLessThanOrEqualTo(String value) {
            addCriterion("bank_statement <=", value, "bankStatement");
            return (Criteria) this;
        }

        public Criteria andBankStatementLike(String value) {
            addCriterion("bank_statement like", value, "bankStatement");
            return (Criteria) this;
        }

        public Criteria andBankStatementNotLike(String value) {
            addCriterion("bank_statement not like", value, "bankStatement");
            return (Criteria) this;
        }

        public Criteria andBankStatementIn(List<String> values) {
            addCriterion("bank_statement in", values, "bankStatement");
            return (Criteria) this;
        }

        public Criteria andBankStatementNotIn(List<String> values) {
            addCriterion("bank_statement not in", values, "bankStatement");
            return (Criteria) this;
        }

        public Criteria andBankStatementBetween(String value1, String value2) {
            addCriterion("bank_statement between", value1, value2, "bankStatement");
            return (Criteria) this;
        }

        public Criteria andBankStatementNotBetween(String value1, String value2) {
            addCriterion("bank_statement not between", value1, value2, "bankStatement");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mall_user_pay
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 29 10:55:34 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mall_user_pay
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}