package com.alpha.mall.manager.pojo;

import java.util.Date;

public class TMallUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_user_info.id_card
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_user_info.user_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_user_info.user_tele_number
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String userTeleNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_user_info.user_birth_place
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String userBirthPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_user_info.user_address
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_user_info.user_gender
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer userGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_user_info.create_time
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_user_info.id_card
     *
     * @return the value of t_mall_user_info.id_card
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_user_info.id_card
     *
     * @param idCard the value for t_mall_user_info.id_card
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setIdCard(Integer idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_user_info.user_id
     *
     * @return the value of t_mall_user_info.user_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_user_info.user_id
     *
     * @param userId the value for t_mall_user_info.user_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_user_info.user_tele_number
     *
     * @return the value of t_mall_user_info.user_tele_number
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getUserTeleNumber() {
        return userTeleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_user_info.user_tele_number
     *
     * @param userTeleNumber the value for t_mall_user_info.user_tele_number
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setUserTeleNumber(String userTeleNumber) {
        this.userTeleNumber = userTeleNumber == null ? null : userTeleNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_user_info.user_birth_place
     *
     * @return the value of t_mall_user_info.user_birth_place
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getUserBirthPlace() {
        return userBirthPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_user_info.user_birth_place
     *
     * @param userBirthPlace the value for t_mall_user_info.user_birth_place
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setUserBirthPlace(String userBirthPlace) {
        this.userBirthPlace = userBirthPlace == null ? null : userBirthPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_user_info.user_address
     *
     * @return the value of t_mall_user_info.user_address
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_user_info.user_address
     *
     * @param userAddress the value for t_mall_user_info.user_address
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_user_info.user_gender
     *
     * @return the value of t_mall_user_info.user_gender
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getUserGender() {
        return userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_user_info.user_gender
     *
     * @param userGender the value for t_mall_user_info.user_gender
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setUserGender(Integer userGender) {
        this.userGender = userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_user_info.create_time
     *
     * @return the value of t_mall_user_info.create_time
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_user_info.create_time
     *
     * @param createTime the value for t_mall_user_info.create_time
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}