package com.alpha.mall.manager.pojo;

public class TMallTmClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_tm_class.Id
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_tm_class.pp_id
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    private Integer ppId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_tm_class.flbh1
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    private Integer flbh1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_tm_class.Id
     *
     * @return the value of t_mall_tm_class.Id
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_tm_class.Id
     *
     * @param id the value for t_mall_tm_class.Id
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_tm_class.pp_id
     *
     * @return the value of t_mall_tm_class.pp_id
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    public Integer getPpId() {
        return ppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_tm_class.pp_id
     *
     * @param ppId the value for t_mall_tm_class.pp_id
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    public void setPpId(Integer ppId) {
        this.ppId = ppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_tm_class.flbh1
     *
     * @return the value of t_mall_tm_class.flbh1
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    public Integer getFlbh1() {
        return flbh1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_tm_class.flbh1
     *
     * @param flbh1 the value for t_mall_tm_class.flbh1
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    public void setFlbh1(Integer flbh1) {
        this.flbh1 = flbh1;
    }
}