package com.alpha.mall.manager.pojo;

public class TMallCkInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_ck_info.id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_ck_info.ck_name
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String ckName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_ck_info.ck_dz
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String ckDz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_ck_info.ck_lx
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String ckLx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_ck_info.ck_mj
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Double ckMj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_ck_info.id
     *
     * @return the value of t_mall_ck_info.id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_ck_info.id
     *
     * @param id the value for t_mall_ck_info.id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_ck_info.ck_name
     *
     * @return the value of t_mall_ck_info.ck_name
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getCkName() {
        return ckName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_ck_info.ck_name
     *
     * @param ckName the value for t_mall_ck_info.ck_name
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setCkName(String ckName) {
        this.ckName = ckName == null ? null : ckName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_ck_info.ck_dz
     *
     * @return the value of t_mall_ck_info.ck_dz
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getCkDz() {
        return ckDz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_ck_info.ck_dz
     *
     * @param ckDz the value for t_mall_ck_info.ck_dz
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setCkDz(String ckDz) {
        this.ckDz = ckDz == null ? null : ckDz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_ck_info.ck_lx
     *
     * @return the value of t_mall_ck_info.ck_lx
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getCkLx() {
        return ckLx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_ck_info.ck_lx
     *
     * @param ckLx the value for t_mall_ck_info.ck_lx
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setCkLx(String ckLx) {
        this.ckLx = ckLx == null ? null : ckLx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_ck_info.ck_mj
     *
     * @return the value of t_mall_ck_info.ck_mj
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Double getCkMj() {
        return ckMj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_ck_info.ck_mj
     *
     * @param ckMj the value for t_mall_ck_info.ck_mj
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setCkMj(Double ckMj) {
        this.ckMj = ckMj;
    }
}