package com.alpha.mall.manager.pojo;

import java.util.Date;

public class TMallFlow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow.id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow.distribution_mode
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String distributionMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow.distribution_time
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Date distributionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow.distribution_descriprion
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String distributionDescriprion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow.user_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow.chj_time
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Date chjTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow.dd_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer ddId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow.mqdd
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String mqdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow.mdd
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String mdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow.ywy
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String ywy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow.lx_mode
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String lxMode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow.id
     *
     * @return the value of t_mall_flow.id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow.id
     *
     * @param id the value for t_mall_flow.id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow.distribution_mode
     *
     * @return the value of t_mall_flow.distribution_mode
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getDistributionMode() {
        return distributionMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow.distribution_mode
     *
     * @param distributionMode the value for t_mall_flow.distribution_mode
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setDistributionMode(String distributionMode) {
        this.distributionMode = distributionMode == null ? null : distributionMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow.distribution_time
     *
     * @return the value of t_mall_flow.distribution_time
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Date getDistributionTime() {
        return distributionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow.distribution_time
     *
     * @param distributionTime the value for t_mall_flow.distribution_time
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setDistributionTime(Date distributionTime) {
        this.distributionTime = distributionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow.distribution_descriprion
     *
     * @return the value of t_mall_flow.distribution_descriprion
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getDistributionDescriprion() {
        return distributionDescriprion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow.distribution_descriprion
     *
     * @param distributionDescriprion the value for t_mall_flow.distribution_descriprion
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setDistributionDescriprion(String distributionDescriprion) {
        this.distributionDescriprion = distributionDescriprion == null ? null : distributionDescriprion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow.user_id
     *
     * @return the value of t_mall_flow.user_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow.user_id
     *
     * @param userId the value for t_mall_flow.user_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow.chj_time
     *
     * @return the value of t_mall_flow.chj_time
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Date getChjTime() {
        return chjTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow.chj_time
     *
     * @param chjTime the value for t_mall_flow.chj_time
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setChjTime(Date chjTime) {
        this.chjTime = chjTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow.dd_id
     *
     * @return the value of t_mall_flow.dd_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getDdId() {
        return ddId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow.dd_id
     *
     * @param ddId the value for t_mall_flow.dd_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setDdId(Integer ddId) {
        this.ddId = ddId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow.mqdd
     *
     * @return the value of t_mall_flow.mqdd
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getMqdd() {
        return mqdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow.mqdd
     *
     * @param mqdd the value for t_mall_flow.mqdd
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setMqdd(String mqdd) {
        this.mqdd = mqdd == null ? null : mqdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow.mdd
     *
     * @return the value of t_mall_flow.mdd
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getMdd() {
        return mdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow.mdd
     *
     * @param mdd the value for t_mall_flow.mdd
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setMdd(String mdd) {
        this.mdd = mdd == null ? null : mdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow.ywy
     *
     * @return the value of t_mall_flow.ywy
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getYwy() {
        return ywy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow.ywy
     *
     * @param ywy the value for t_mall_flow.ywy
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setYwy(String ywy) {
        this.ywy = ywy == null ? null : ywy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow.lx_mode
     *
     * @return the value of t_mall_flow.lx_mode
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getLxMode() {
        return lxMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow.lx_mode
     *
     * @param lxMode the value for t_mall_flow.lx_mode
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setLxMode(String lxMode) {
        this.lxMode = lxMode == null ? null : lxMode.trim();
    }
}