package com.alpha.mall.manager.pojo;

import java.util.Date;

public class TMallShoppingcar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.Id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.sku_name
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String skuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.sku_price
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Short skuPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.add_count
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer addCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.total
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Long total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.user_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.shp_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer shpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.chj_time
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Date chjTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.sku_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private Integer skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.shp_pic
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String shpPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.is_selected
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String isSelected;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.kcdz
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    private String kcdz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.Id
     *
     * @return the value of t_mall_shoppingcar.Id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.Id
     *
     * @param id the value for t_mall_shoppingcar.Id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.sku_name
     *
     * @return the value of t_mall_shoppingcar.sku_name
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getSkuName() {
        return skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.sku_name
     *
     * @param skuName the value for t_mall_shoppingcar.sku_name
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setSkuName(String skuName) {
        this.skuName = skuName == null ? null : skuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.sku_price
     *
     * @return the value of t_mall_shoppingcar.sku_price
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Short getSkuPrice() {
        return skuPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.sku_price
     *
     * @param skuPrice the value for t_mall_shoppingcar.sku_price
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setSkuPrice(Short skuPrice) {
        this.skuPrice = skuPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.add_count
     *
     * @return the value of t_mall_shoppingcar.add_count
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getAddCount() {
        return addCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.add_count
     *
     * @param addCount the value for t_mall_shoppingcar.add_count
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setAddCount(Integer addCount) {
        this.addCount = addCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.total
     *
     * @return the value of t_mall_shoppingcar.total
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Long getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.total
     *
     * @param total the value for t_mall_shoppingcar.total
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setTotal(Long total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.user_id
     *
     * @return the value of t_mall_shoppingcar.user_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.user_id
     *
     * @param userId the value for t_mall_shoppingcar.user_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.shp_id
     *
     * @return the value of t_mall_shoppingcar.shp_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getShpId() {
        return shpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.shp_id
     *
     * @param shpId the value for t_mall_shoppingcar.shp_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setShpId(Integer shpId) {
        this.shpId = shpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.chj_time
     *
     * @return the value of t_mall_shoppingcar.chj_time
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Date getChjTime() {
        return chjTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.chj_time
     *
     * @param chjTime the value for t_mall_shoppingcar.chj_time
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setChjTime(Date chjTime) {
        this.chjTime = chjTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.sku_id
     *
     * @return the value of t_mall_shoppingcar.sku_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.sku_id
     *
     * @param skuId the value for t_mall_shoppingcar.sku_id
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.shp_pic
     *
     * @return the value of t_mall_shoppingcar.shp_pic
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getShpPic() {
        return shpPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.shp_pic
     *
     * @param shpPic the value for t_mall_shoppingcar.shp_pic
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setShpPic(String shpPic) {
        this.shpPic = shpPic == null ? null : shpPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.is_selected
     *
     * @return the value of t_mall_shoppingcar.is_selected
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getIsSelected() {
        return isSelected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.is_selected
     *
     * @param isSelected the value for t_mall_shoppingcar.is_selected
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setIsSelected(String isSelected) {
        this.isSelected = isSelected == null ? null : isSelected.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.kcdz
     *
     * @return the value of t_mall_shoppingcar.kcdz
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public String getKcdz() {
        return kcdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.kcdz
     *
     * @param kcdz the value for t_mall_shoppingcar.kcdz
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    public void setKcdz(String kcdz) {
        this.kcdz = kcdz == null ? null : kcdz.trim();
    }
}