package com.alpha.mall.manager.dao;

import com.alpha.mall.manager.pojo.TMallPayFlowInfoLog;
import com.alpha.mall.manager.pojo.TMallPayFlowInfoLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TMallPayFlowInfoLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_pay_flow_info_log
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int countByExample(TMallPayFlowInfoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_pay_flow_info_log
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int deleteByExample(TMallPayFlowInfoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_pay_flow_info_log
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_pay_flow_info_log
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int insert(TMallPayFlowInfoLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_pay_flow_info_log
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int insertSelective(TMallPayFlowInfoLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_pay_flow_info_log
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    List<TMallPayFlowInfoLog> selectByExample(TMallPayFlowInfoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_pay_flow_info_log
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") TMallPayFlowInfoLog record, @Param("example") TMallPayFlowInfoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_pay_flow_info_log
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByExample(@Param("record") TMallPayFlowInfoLog record, @Param("example") TMallPayFlowInfoLogExample example);
}