package com.alpha.mall.manager.dao;

import com.alpha.mall.manager.pojo.TMallOrder;
import com.alpha.mall.manager.pojo.TMallOrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TMallOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_order
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int countByExample(TMallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_order
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int deleteByExample(TMallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_order
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_order
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int insert(TMallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_order
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int insertSelective(TMallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_order
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    List<TMallOrder> selectByExample(TMallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_order
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    TMallOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_order
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") TMallOrder record, @Param("example") TMallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_order
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByExample(@Param("record") TMallOrder record, @Param("example") TMallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_order
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByPrimaryKeySelective(TMallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_order
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByPrimaryKey(TMallOrder record);
}