package com.alpha.mall.manager.dao;

import com.alpha.mall.manager.pojo.TMallSkuAttrValue;
import com.alpha.mall.manager.pojo.TMallSkuAttrValueExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TMallSkuAttrValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_sku_attr_value
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int countByExample(TMallSkuAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_sku_attr_value
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int deleteByExample(TMallSkuAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_sku_attr_value
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_sku_attr_value
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int insert(TMallSkuAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_sku_attr_value
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int insertSelective(TMallSkuAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_sku_attr_value
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    List<TMallSkuAttrValue> selectByExample(TMallSkuAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_sku_attr_value
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    TMallSkuAttrValue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_sku_attr_value
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") TMallSkuAttrValue record, @Param("example") TMallSkuAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_sku_attr_value
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByExample(@Param("record") TMallSkuAttrValue record, @Param("example") TMallSkuAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_sku_attr_value
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByPrimaryKeySelective(TMallSkuAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_sku_attr_value
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByPrimaryKey(TMallSkuAttrValue record);
}