package com.alpha.mall.manager.dao;


import com.alpha.mall.manager.pojo.TMallOrderPhase;
import com.alpha.mall.manager.pojo.TMallOrderPhaseExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TMallOrderPhaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_order_phase
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int countByExample(TMallOrderPhaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_order_phase
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int deleteByExample(TMallOrderPhaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_order_phase
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_order_phase
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int insert(TMallOrderPhase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_order_phase
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int insertSelective(TMallOrderPhase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_order_phase
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    List<TMallOrderPhase> selectByExample(TMallOrderPhaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_order_phase
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    TMallOrderPhase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_order_phase
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") TMallOrderPhase record, @Param("example") TMallOrderPhaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_order_phase
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int updateByExample(@Param("record") TMallOrderPhase record, @Param("example") TMallOrderPhaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_order_phase
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int updateByPrimaryKeySelective(TMallOrderPhase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_order_phase
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int updateByPrimaryKey(TMallOrderPhase record);
}