package com.alpha.mall.manager.dao;


import com.alpha.mall.manager.pojo.TMallProduct;
import com.alpha.mall.manager.pojo.TMallProductExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TMallProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int countByExample(TMallProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int deleteByExample(TMallProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int insert(TMallProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int insertSelective(TMallProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    List<TMallProduct> selectByExample(TMallProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    TMallProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") TMallProduct record, @Param("example") TMallProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int updateByExample(@Param("record") TMallProduct record, @Param("example") TMallProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int updateByPrimaryKeySelective(TMallProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int updateByPrimaryKey(TMallProduct record);
}