package com.alpha.mall.manager.dao;

import com.alpha.mall.manager.pojo.TMallProductSkuInfo;
import com.alpha.mall.manager.pojo.TMallProductSkuInfoExample;
import com.alpha.mall.manager.pojo.TMallProductSkuInfoKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TMallProductSkuInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int countByExample(TMallProductSkuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int deleteByExample(TMallProductSkuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int deleteByPrimaryKey(TMallProductSkuInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int insert(TMallProductSkuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int insertSelective(TMallProductSkuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    List<TMallProductSkuInfo> selectByExample(TMallProductSkuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    TMallProductSkuInfo selectByPrimaryKey(TMallProductSkuInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") TMallProductSkuInfo record, @Param("example") TMallProductSkuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByExample(@Param("record") TMallProductSkuInfo record, @Param("example") TMallProductSkuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByPrimaryKeySelective(TMallProductSkuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_sku_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByPrimaryKey(TMallProductSkuInfo record);
}