package com.alpha.mall.manager.dao;

import com.alpha.mall.manager.pojo.TMallShoppingcar;
import com.alpha.mall.manager.pojo.TMallShoppingcarExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TMallShoppingcarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int countByExample(TMallShoppingcarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int deleteByExample(TMallShoppingcarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int insert(TMallShoppingcar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int insertSelective(TMallShoppingcar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    List<TMallShoppingcar> selectByExample(TMallShoppingcarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    TMallShoppingcar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") TMallShoppingcar record, @Param("example") TMallShoppingcarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByExample(@Param("record") TMallShoppingcar record, @Param("example") TMallShoppingcarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByPrimaryKeySelective(TMallShoppingcar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByPrimaryKey(TMallShoppingcar record);
}