package com.alpha.mall.manager.dao;

import com.alpha.mall.manager.pojo.TMallShoppingcarInfo;
import com.alpha.mall.manager.pojo.TMallShoppingcarInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TMallShoppingcarInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int countByExample(TMallShoppingcarInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int deleteByExample(TMallShoppingcarInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int insert(TMallShoppingcarInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int insertSelective(TMallShoppingcarInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    List<TMallShoppingcarInfo> selectByExample(TMallShoppingcarInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    TMallShoppingcarInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") TMallShoppingcarInfo record, @Param("example") TMallShoppingcarInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByExample(@Param("record") TMallShoppingcarInfo record, @Param("example") TMallShoppingcarInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByPrimaryKeySelective(TMallShoppingcarInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_shoppingcar_info
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByPrimaryKey(TMallShoppingcarInfo record);
}