package com.alpha.mall.manager.dao;


import com.alpha.mall.manager.pojo.TMallProductVersion;
import com.alpha.mall.manager.pojo.TMallProductVersionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TMallProductVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_version
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int countByExample(TMallProductVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_version
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int deleteByExample(TMallProductVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_version
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_version
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int insert(TMallProductVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_version
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int insertSelective(TMallProductVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_version
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    List<TMallProductVersion> selectByExample(TMallProductVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_version
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    TMallProductVersion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_version
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") TMallProductVersion record, @Param("example") TMallProductVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_version
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int updateByExample(@Param("record") TMallProductVersion record, @Param("example") TMallProductVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_version
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int updateByPrimaryKeySelective(TMallProductVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_version
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int updateByPrimaryKey(TMallProductVersion record);
}