package com.alpha.mall.manager.dao;


import com.alpha.mall.manager.pojo.TMallSkuImage;
import com.alpha.mall.manager.pojo.TMallSkuImageExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TMallSkuImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_sku_image
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    int countByExample(TMallSkuImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_sku_image
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    int deleteByExample(TMallSkuImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_sku_image
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_sku_image
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    int insert(TMallSkuImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_sku_image
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    int insertSelective(TMallSkuImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_sku_image
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    List<TMallSkuImage> selectByExample(TMallSkuImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_sku_image
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    TMallSkuImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_sku_image
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") TMallSkuImage record, @Param("example") TMallSkuImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_sku_image
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    int updateByExample(@Param("record") TMallSkuImage record, @Param("example") TMallSkuImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_sku_image
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    int updateByPrimaryKeySelective(TMallSkuImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_sku_image
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    int updateByPrimaryKey(TMallSkuImage record);
}