package com.alpha.mall.manager.dao;


import com.alpha.mall.manager.pojo.TMallClass1;
import com.alpha.mall.manager.pojo.TMallClass1Example;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TMallClass1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_class_1
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int countByExample(TMallClass1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_class_1
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int deleteByExample(TMallClass1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_class_1
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_class_1
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int insert(TMallClass1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_class_1
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int insertSelective(TMallClass1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_class_1
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    List<TMallClass1> selectByExample(TMallClass1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_class_1
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    TMallClass1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_class_1
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") TMallClass1 record, @Param("example") TMallClass1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_class_1
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int updateByExample(@Param("record") TMallClass1 record, @Param("example") TMallClass1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_class_1
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int updateByPrimaryKeySelective(TMallClass1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_class_1
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int updateByPrimaryKey(TMallClass1 record);
}