package com.alpha.mall.manager.dao;


import com.alpha.mall.manager.pojo.TMallUserInfo;
import com.alpha.mall.manager.pojo.TMallUserInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TMallUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_user_info
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    int countByExample(TMallUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_user_info
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    int deleteByExample(TMallUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_user_info
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    int deleteByPrimaryKey(Integer idCard);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_user_info
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    int insert(TMallUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_user_info
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    int insertSelective(TMallUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_user_info
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    List<TMallUserInfo> selectByExample(TMallUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_user_info
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    TMallUserInfo selectByPrimaryKey(Integer idCard);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_user_info
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") TMallUserInfo record, @Param("example") TMallUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_user_info
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    int updateByExample(@Param("record") TMallUserInfo record, @Param("example") TMallUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_user_info
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    int updateByPrimaryKeySelective(TMallUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_user_info
     *
     * @mbggenerated Thu Jan 25 17:08:31 CST 2018
     */
    int updateByPrimaryKey(TMallUserInfo record);
}