package com.alpha.mall.manager.dao;

import com.alpha.mall.manager.pojo.TMallProductComment;
import com.alpha.mall.manager.pojo.TMallProductCommentExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TMallProductCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int countByExample(TMallProductCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int deleteByExample(TMallProductCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int insert(TMallProductComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int insertSelective(TMallProductComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    List<TMallProductComment> selectByExample(TMallProductCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    TMallProductComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") TMallProductComment record, @Param("example") TMallProductCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByExample(@Param("record") TMallProductComment record, @Param("example") TMallProductCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByPrimaryKeySelective(TMallProductComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_comment
     *
     * @mbggenerated Mon Jan 29 10:55:34 CST 2018
     */
    int updateByPrimaryKey(TMallProductComment record);
}