package com.alpha.mall.manager.dao;


import com.alpha.mall.manager.pojo.TMallProductColor;
import com.alpha.mall.manager.pojo.TMallProductColorExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TMallProductColorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_color
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int countByExample(TMallProductColorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_color
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int deleteByExample(TMallProductColorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_color
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_color
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int insert(TMallProductColor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_color
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int insertSelective(TMallProductColor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_color
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    List<TMallProductColor> selectByExample(TMallProductColorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_color
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    TMallProductColor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_color
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") TMallProductColor record, @Param("example") TMallProductColorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_color
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int updateByExample(@Param("record") TMallProductColor record, @Param("example") TMallProductColorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_color
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int updateByPrimaryKeySelective(TMallProductColor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_product_color
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int updateByPrimaryKey(TMallProductColor record);
}