package com.alpha.mall.manager.dao;


import com.alpha.mall.manager.pojo.TMallSearchInfoLog;
import com.alpha.mall.manager.pojo.TMallSearchInfoLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TMallSearchInfoLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_search_info_log
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int countByExample(TMallSearchInfoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_search_info_log
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int deleteByExample(TMallSearchInfoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_search_info_log
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_search_info_log
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int insert(TMallSearchInfoLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_search_info_log
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int insertSelective(TMallSearchInfoLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_search_info_log
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    List<TMallSearchInfoLog> selectByExample(TMallSearchInfoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_search_info_log
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") TMallSearchInfoLog record, @Param("example") TMallSearchInfoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_search_info_log
     *
     * @mbggenerated Thu Jan 25 17:08:30 CST 2018
     */
    int updateByExample(@Param("record") TMallSearchInfoLog record, @Param("example") TMallSearchInfoLogExample example);
}